### ISSUE TITLE
bare integers don't work as keys

### ISSUE THREAD

**Issue by Cloven** [avakar/pytoml#3]
From the spec:

"Keys may be either bare or quoted. Bare keys may only contain letters, numbers, underscores, and dashes (A-Za-z0-9_-)."

Test case:

5="bruce"

Result:

pytoml.core.TomlError: script.bb(1, 1): unexpected

Reason:

By the time pytoml has gotten to the question of whether a token is an id, it has already checked to see if it is a datetime or a float; or failed back to int if it was neither a datetime or a float.

However, what it should do is instead check to see if there's an equals sign (possibly after some amount of whitespace) after the int, and if there is, mark it as an id.

**Comment by avakar** [comment]
Thanks to bringing this to my attention. I didn't notice that keys are allowed to start with a digit, which makes two-phase parsing rather cumbersome. The issue also seems to affect table names. I can't actually accept int tokens as keys, as otherwise "+1" would be a valid key, so the fix won't be that easy. I'll see what I can do though.

**Comment by avakar** [comment]
@Cloven, I've uploaded a new version to pypi with the parser completely rewritten. It should accept numeric-only keys now.

**Comment by Cloven** [comment]
Nice, well done.  Looks a lot cleaner.  Will test it out soon.
